<?php

function ice_charts_init(){
}


function ice_charts_block_info() {
  $blocks = array();
  $blocks['ice_charts_block'] = array(
    'info' => t('Ice Charts Module'),
  );
  return $blocks;
}

function ice_charts_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'ice_charts_block':
     $block['content'] = ice_charts_main_content(); // set the content of the block to our ice_charts_main_content
     break;
  }
  return $block;
}


function ice_charts_main_content(){
  global $base_url;
  global $metsis_conf;
  
  $mpath = drupal_get_path('module', 'ice_charts');
  $ol3_path = libraries_get_path('openlayers5');
  $jq_path = drupal_get_path('module', 'jquery_update');
  drupal_add_js($jq_path . '/replace/ui/ui/jquery.ui.datepicker.js');
  drupal_add_css($jq_path . '/replace/ui/themes/base/jquery.ui.datepicker.css');

  drupal_add_css($mpath . '/css/ice_charts_style.css');
  drupal_add_css($ol3_path . '/css/ol.css');

  drupal_add_js($ol3_path . '/build/ol.js');
  drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.15/proj4.js', 'external');

return '
<div id="map" class="map" >
</div>


<div class="controls">

<label>Select a date with the time slider: </label>
<script type="text/javascript">
   var sliderStartDay = Math.floor(new Date("2010-01-04T14:00:00.000Z")/8.64e7).toString();
   var nowOrYester = new Date();
   if (nowOrYester.getUTCHours() < 14){
     nowOrYester.setUTCDate(nowOrYester.getUTCDate() - 1);
   }
   var sliderEndDay = Math.floor(nowOrYester/8.64e7).toString();

   document.write("<input id=\"ic-slider\" type=\"range\" min=\""
                + sliderStartDay + "\" max=\"" + sliderEndDay
                + "\" value=\"" + sliderEndDay + "\" />");
</script>

<label>Or, navigate on the calendar: </label>
<button class="prev-month btn btn-outline-secondary" ><i class="arrow left"></i><i class="arrow left"></i></button>
<button class="prev-day btn btn-outline-secondary"><i class="arrow left"></i></button>
<input type="dateTime" id="datepicker"  name="datepicker" readonly="true">
<button class="next-day btn btn-outline-secondary" ><i class="arrow right"></i></button>
<button class="next-month btn btn-outline-secondary" ><i class="arrow right"></i><i class="arrow right"></i></button>

<script type="text/javascript">

   function datepicker_onchange (newDate) {
       var new_day = Math.floor(newDate/8.64e7).toString();
       if (document.getElementById("ic-slider").value != new_day) {
           document.getElementById("ic-slider").value = new_day;
           jQuery("#ic-slider").trigger("change");
       }
   } 

   jQuery("#datepicker").datepicker({dateFormat: "yy-mm-ddT14:00:00.000Z"});
   var fill_picker = new Date(parseInt(document.getElementById("ic-slider").value)*8.64e7);
   fill_picker.setUTCHours(14);
   jQuery("#datepicker").datepicker("setDate", fill_picker);
   jQuery("#datepicker").on("change", function() {
       datepicker_onchange(new Date(this.value));
   });

   jQuery(".next-day").on("click", function () {
       var date = new Date(document.getElementById("datepicker").value);
       date.setDate(date.getDate() +1)
       jQuery("#datepicker").datepicker("setDate", date);
       datepicker_onchange(date);
   });
   jQuery(".next-month").on("click", function () {
       var date = new Date(document.getElementById("datepicker").value);
       date.setMonth(date.getMonth() + 1);
       jQuery("#datepicker").datepicker("setDate", date);
       datepicker_onchange(date);
   });
   jQuery(".prev-day").on("click", function () {
       var date = new Date(document.getElementById("datepicker").value);
       date.setDate(date.getDate() -1)
       jQuery("#datepicker").datepicker("setDate", date);
       datepicker_onchange(date);
   });
   jQuery(".prev-month").on("click", function () {
       var date = new Date(document.getElementById("datepicker").value);
       date.setMonth(date.getMonth() -1);
       jQuery("#datepicker").datepicker("setDate", date);
       datepicker_onchange(date);
   });
</script>

    <!--label>Acquisition: </label-->
    <div id="boxDate"></div>

</div>
   <script type="text/javascript" src="/'.$mpath.'/js/ice_charts.js"></script>
<center>
<br>
<table style="width:50%">
   <tr align=center><th>Colour</th><th>Total Concentration</th></tr>
   <tr align=center><td bgcolor= #969696></td><td>Fast Ice</td></tr>
   <tr align=center><td bgcolor= #FF0000></td><td>Very Close Ice</td></tr>
   <tr align=center><td bgcolor= #FF7D07></td><td>Close Ice</td></tr>
   <tr align=center><td bgcolor= #FFFF00></td><td>Open Ice</td></tr>
   <tr align=center><td bgcolor= #8CFFA0></td><td>Very Open Ice</td></tr>
   <tr align=center><td bgcolor= #96c9ff></td><td>Open Water</td></tr>
</table>
</center>

';
}
?>
