<?php

function ice_charts_init(){
  $mpath = drupal_get_path('module', 'ice_charts');
  drupal_add_css($mpath . '/css/ice_charts_style.css');
}


function ice_charts_block_info() {
  $blocks = array();
  $blocks['ice_charts_block'] = array(
    'info' => t('Ice Charts Module'),
  );
  return $blocks;
}

function ice_charts_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'ice_charts_block':
     $block['content'] = ice_charts_main_content(); // set the content of the block to our mosaic_main_content
     break;
  }
  return $block;
}


function ice_charts_main_content(){
  global $base_url;
  global $metsis_conf;
  
  $site_name = variable_get('site_name', 'Default');
  $scr_name = $base_url ."/ice_charts";
  $mpath = drupal_get_path('module', 'ice_charts');

// define first array with dummy values for "date, id, address, latlong" 
  $day = (new DateTime())->modify('-4 day')->format('Y-m-d\TH:i:s\Z'); //today
  //drupal_set_message(print_r($day,TRUE),'warning');
  //drupal_set_message(print_r($day,TRUE),'warning');

// Make 4 different queries depending on AREA which they will be shown switching between tabs 
// Q1 tllong(minx): -3.22; brlong(maxx): 55.29;  tllat(maxy): 83.21; brlat(miny): 72.70

  $prinfoQ1 = [];
  $queryQ1_res = [];

  // Define queries and extract prinfo
  $envQ1 = [-2.22, 52.29, 82.21, 72.70];

  $queryQ1_prd = 'mmd_temporal_extent_start_date:['.$day.' TO *] AND bbox:"Intersects(ENVELOPE(-2.22, 52.29, 82.21, 72.70))"';
  $fields = "id, mmd_data_access_resource, mmd_temporal_extent_start_date, mmd_temporal_extent_end_date, mmd_geographic_extent_rectangle_north, mmd_geographic_extent_rectangle_south, mmd_geographic_extent_rectangle_east, mmd_geographic_extent_rectangle_west, mmd_data_access_wms_layers_wms_layer";
   
  // Define connection to SolR and results of the query
  $con1 = new HttpConnection(SOLR_SERVER_IP, SOLR_SERVER_PORT);
  $resQ1 = $con1->get('/solr/nbs-l1/select', array("q" =>$queryQ1_prd, "start" => 0, "rows" => 1000, "wt" => "json", "fl" => $fields,));
  $queryQ1_res = json_decode($resQ1['body'], true);


  $count = 0; 
  foreach ($queryQ1_res['response']['docs'] as $doc) {
     $id = $doc['id'];
     $address = $doc['mmd_data_access_resource'][1];
     $address = json_decode("{".$address."}",true)['OGC WMS'];
     $start = $doc['mmd_temporal_extent_start_date'];
     $end = $doc['mmd_temporal_extent_end_date'];
     $north = $doc['mmd_geographic_extent_rectangle_north'];
     $south = $doc['mmd_geographic_extent_rectangle_south'];
     $east = $doc['mmd_geographic_extent_rectangle_east'];
     $west = $doc['mmd_geographic_extent_rectangle_west'];
     $layers = $doc['mmd_data_access_wms_layers_wms_layer'];
     $latlon = array(($south+$north)/2, ($east+$west)/2);
     $prinfoQ1[$count] = array($address, $id, $layers, array($north,$south,$east,$west), array($start, $end));
     $count = $count + 1; 
  }

  drupal_json_encode($prinfoQ1);
  drupal_add_js(array('prinfoQ1' => $prinfoQ1
                      ), 'setting');
  

return '

<!doctype html>                                                                                                                                                                                                         
<html lang="en">                                                                                                                                                                                                        
  <head>                                                                                                                                          
    <script src="/'.drupal_get_path('module','jquery_update').'/replace/jquery/1.10/jquery.min.js"></script>

    <link rel="stylesheet" href="/'.libraries_get_path('openlayers3').'/css/ol.css" type="text/css">
    <link rel="stylesheet" href="/'.libraries_get_path('openlayers3').'/apidoc/styles/bootstrap.min.css">
    <link rel="stylesheet" href="/'.libraries_get_path('ol3-layerswitcher').'/src/ol3-layerswitcher.css">
    <script src="/'.libraries_get_path('openlayers3').'/build/ol.js" type="text/javascript"></script>
    <script src="/'.libraries_get_path('openlayers3').'/apidoc/scripts/bootstrap.min.js"></script>
    <script src="/'.libraries_get_path('ol3-layerswitcher').'/src/ol3-layerswitcher.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.15/proj4.js"></script>
  </head>
  <body>
    <div id="map" class="map" >
       <script type="text/javascript" src="/'.$mpath.'/js/ice_charts.js"></script>
    </div>
  </body>
</html>
';
}
?>
